# Generated by Django 6.0.4 on 2026-05-23 09:17

import django.db.models.deletion
import django.utils.timezone
import pharmacy.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_rename_patients_pat_next_fo_9f6674_idx_patients_pa_next_fo_ee0511_idx'),
        ('visits', '0003_visitsession_file_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispenseInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=30, unique=True)),
                ('display_invoice_number', models.CharField(blank=True, default='', max_length=50)),
                ('dispense_date', models.DateField(default=django.utils.timezone.localdate)),
                ('dispense_time', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online / Digital Payment'), ('Split', 'Split Payment (Cash + Online)')], default='Cash', max_length=10)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('online_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('cancelled', 'Cancelled')], default='success', max_length=10)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispenses_cancelled', to=settings.AUTH_USER_MODEL)),
                ('dispensed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispense_invoices', to='patients.patient')),
                ('visit_session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispense_invoice', to='visits.visitsession')),
            ],
            options={
                'ordering': ['-dispense_time'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('BUP', 'BUP (Controlled Substance)'), ('Rx', 'Rx (Prescription Only)'), ('NRx', 'NRx (Non-Prescription / General)')], max_length=10)),
                ('bup_category', models.CharField(blank=True, choices=[('0.4mg + 0.1mg', 'Buprenorphine 0.4mg + Naloxone 0.1mg'), ('1.0mg + 0.25mg', 'Buprenorphine 1.0mg + Naloxone 0.25mg'), ('2.0mg + 0.5mg', 'Buprenorphine 2.0mg + Naloxone 0.5mg')], max_length=20, null=True)),
                ('manufacturer', models.CharField(max_length=255)),
                ('reorder_level', models.PositiveIntegerField(default=50)),
                ('tablets_per_strip', models.PositiveIntegerField(default=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('deletion_reason', models.CharField(blank=True, default='', max_length=255)),
                ('deletion_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField(default=0)),
                ('initial_quantity', models.PositiveIntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy.medicine')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='DispenseInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=10)),
                ('batch_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('dose', models.CharField(max_length=20)),
                ('days', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispense_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.dispenseinvoice')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medicine')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medicinebatch')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('supplier', models.CharField(max_length=255)),
                ('invoice_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('invoice_photo', models.FileField(blank=True, null=True, upload_to=pharmacy.models.purchase_invoice_upload_path)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('items_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to='pharmacy.purchaseinvoice'),
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=10)),
                ('subcategory', models.CharField(blank=True, default='', max_length=20)),
                ('batch_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medicinebatch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medicine')),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.purchaseinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='StockAuditRemoval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=50)),
                ('quantity_removed', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('destroyed', 'Destroyed'), ('returned', 'Returned to Supplier'), ('damaged', 'Damaged'), ('defect', 'Manufacturing Defect')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('audit_document', models.FileField(blank=True, null=True, upload_to=pharmacy.models.audit_removal_upload_path)),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medicinebatch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medicine')),
                ('removed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_removals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-removed_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase / Stock In'), ('dispense', 'Dispense / Stock Out'), ('audit_removal', 'Audit Removal'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('quantity_change', models.IntegerField()),
                ('quantity_before', models.IntegerField()),
                ('quantity_after', models.IntegerField()),
                ('reference_type', models.CharField(blank=True, default='', max_length=30)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medicinebatch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medicine')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dispenseinvoice',
            index=models.Index(fields=['patient', '-dispense_date'], name='pharmacy_di_patient_05d24c_idx'),
        ),
        migrations.AddIndex(
            model_name='dispenseinvoice',
            index=models.Index(fields=['-dispense_date'], name='pharmacy_di_dispens_c84541_idx'),
        ),
        migrations.AddIndex(
            model_name='dispenseinvoice',
            index=models.Index(fields=['dispensed_by', '-dispense_date'], name='pharmacy_di_dispens_4385e1_idx'),
        ),
        migrations.AddIndex(
            model_name='dispenseinvoice',
            index=models.Index(fields=['payment_method'], name='pharmacy_di_payment_664d62_idx'),
        ),
        migrations.AddIndex(
            model_name='dispenseinvoice',
            index=models.Index(fields=['status'], name='pharmacy_di_status_b2f98e_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispenseinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percentage__gte', 0), ('discount_percentage__lte', 100)), name='pharmacy_valid_discount_percentage'),
        ),
        migrations.AddConstraint(
            model_name='dispenseinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('cash_amount__gte', 0)), name='pharmacy_non_negative_cash'),
        ),
        migrations.AddConstraint(
            model_name='dispenseinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('online_amount__gte', 0)), name='pharmacy_non_negative_online'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['category'], name='pharmacy_me_categor_6b0964_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['is_active'], name='pharmacy_me_is_acti_1c529c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['category', 'bup_category'], name='pharmacy_me_categor_9a751e_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name', 'category', 'bup_category'), name='pharmacy_unique_active_medicine'),
        ),
        migrations.AddIndex(
            model_name='dispenseinvoiceitem',
            index=models.Index(fields=['dispense_invoice'], name='pharmacy_di_dispens_6e605d_idx'),
        ),
        migrations.AddIndex(
            model_name='dispenseinvoiceitem',
            index=models.Index(fields=['medicine', '-created_at'], name='pharmacy_di_medicin_525188_idx'),
        ),
        migrations.AddIndex(
            model_name='dispenseinvoiceitem',
            index=models.Index(fields=['batch'], name='pharmacy_di_batch_i_8a5d24_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['supplier'], name='pharmacy_pu_supplie_4db8d5_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['invoice_date'], name='pharmacy_pu_invoice_3c84cd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['-created_at'], name='pharmacy_pu_created_144dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['medicine', 'expiry_date'], name='pharmacy_me_medicin_8410d3_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['expiry_date'], name='pharmacy_me_expiry__40e328_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['is_active'], name='pharmacy_me_is_acti_6bd23a_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicinebatch',
            constraint=models.UniqueConstraint(fields=('medicine', 'batch_number'), name='pharmacy_unique_medicine_batch'),
        ),
        migrations.AddConstraint(
            model_name='medicinebatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='pharmacy_non_negative_batch_qty'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoiceitem',
            index=models.Index(fields=['purchase_invoice'], name='pharmacy_pu_purchas_70cab9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoiceitem',
            index=models.Index(fields=['medicine'], name='pharmacy_pu_medicin_92e737_idx'),
        ),
        migrations.AddIndex(
            model_name='stockauditremoval',
            index=models.Index(fields=['medicine'], name='pharmacy_st_medicin_f4e441_idx'),
        ),
        migrations.AddIndex(
            model_name='stockauditremoval',
            index=models.Index(fields=['batch'], name='pharmacy_st_batch_i_0c254a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockauditremoval',
            index=models.Index(fields=['reason'], name='pharmacy_st_reason_00fb70_idx'),
        ),
        migrations.AddIndex(
            model_name='stockauditremoval',
            index=models.Index(fields=['-removed_at'], name='pharmacy_st_removed_2dc64e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['medicine', '-performed_at'], name='pharmacy_st_medicin_96ad9c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['batch', '-performed_at'], name='pharmacy_st_batch_i_5e0aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='pharmacy_st_movemen_ec6bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['-performed_at'], name='pharmacy_st_perform_55a436_idx'),
        ),
    ]
