# Generated by Django 6.0.4 on 2026-05-31 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_supplier_and_purchase_invoice_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='purchaseinvoice',
            new_name='pharmacy_pu_supplie_a3bbcf_idx',
            old_name='pharmacy_pu_supplie_fk_idx',
        ),
        migrations.RenameIndex(
            model_name='supplier',
            new_name='pharmacy_su_is_acti_1de97d_idx',
            old_name='pharmacy_su_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='supplier',
            new_name='pharmacy_su_company_4f6054_idx',
            old_name='pharmacy_su_company_idx',
        ),
    ]
