# Generated by Django 6.0.4 on 2026-06-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_purchaseinvoice_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='medicines', to='pharmacy.supplier'),
        ),
    ]
