# Generated by Django 6.0.4 on 2026-06-10 19:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_medicine_suppliers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispenseInvoiceAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amended_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=255)),
                ('previous_state', models.JSONField()),
                ('amended_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispense_amendments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='pharmacy.dispenseinvoice')),
            ],
            options={
                'verbose_name': 'Dispense Invoice Amendment',
                'verbose_name_plural': 'Dispense Invoice Amendments',
                'ordering': ['-amended_at'],
                'indexes': [models.Index(fields=['invoice', '-amended_at'], name='pharmacy_di_invoice_45d219_idx')],
            },
        ),
    ]
