# Generated by Django 6.0.4 on 2026-06-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_dispenseinvoiceamendment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenseinvoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dispenseinvoice',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
