# Generated by Django 6.0.4 on 2026-06-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_backfill_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='form6',
            field=models.BooleanField(default=False),
        ),
    ]
