# Generated by Django 6.0.4 on 2026-06-16 08:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_purchaseinvoice_form6'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='outstanding_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='SupplierLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('invoice', 'Invoice (payable booked)'), ('payment', 'Payment made'), ('adjustment', 'Adjustment / Reversal')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(blank=True, default='', max_length=16)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_ledger_entries_created', to=settings.AUTH_USER_MODEL)),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='pharmacy.purchaseinvoice')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='pharmacy.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Ledger Entry',
                'verbose_name_plural': 'Supplier Ledger Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['supplier', '-created_at'], name='pharmacy_su_supplie_89e180_idx'), models.Index(fields=['purchase_invoice'], name='pharmacy_su_purchas_fd73e9_idx'), models.Index(fields=['entry_type'], name='pharmacy_su_entry_t_7ec702_idx')],
            },
        ),
    ]
