# Generated by Django 6.0.4 on 2026-06-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_backfill_supplier_invoice_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierledgerentry',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
