# Generated by Django 6.0.4 on 2026-04-09 21:20

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=32, unique=True)),
                ('hdams_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('patient_category', models.CharField(choices=[('psychiatric', 'Psychiatric'), ('deaddiction', 'De-Addiction')], max_length=32)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=16)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('relative_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.TextField()),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('fingerprint_template', models.TextField(blank=True)),
                ('fingerprint_enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('fingerprint_template_key_version', models.CharField(default='v1', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('dead', 'Dead'), ('discharged', 'Discharged'), ('follow_up', 'Follow Up')], default='active', max_length=32)),
                ('outstanding_debt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('registration_date', models.DateField(default=django.utils.timezone.localdate)),
                ('mother_name', models.CharField(blank=True, max_length=255)),
                ('father_name', models.CharField(blank=True, max_length=255)),
                ('grandfather_name', models.CharField(blank=True, max_length=255)),
                ('spouse_name', models.CharField(blank=True, max_length=255)),
                ('blood_group', models.CharField(blank=True, max_length=8)),
                ('nationality', models.CharField(blank=True, max_length=64)),
                ('religion', models.CharField(blank=True, max_length=64)),
                ('monthly_income', models.CharField(blank=True, max_length=64)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('employment_status', models.CharField(blank=True, max_length=64)),
                ('education', models.CharField(blank=True, max_length=64)),
                ('marital_status', models.CharField(blank=True, max_length=64)),
                ('block_mc', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('pincode', models.CharField(blank=True, max_length=16)),
                ('living_arrangement', models.CharField(blank=True, max_length=64)),
                ('substance_used_currently', models.JSONField(blank=True, default=list)),
                ('substance_ever_used', models.JSONField(blank=True, default=list)),
                ('injection_use_ever', models.BooleanField(default=False)),
                ('injection_use_currently', models.BooleanField(default=False)),
                ('route_of_admission', models.CharField(blank=True, max_length=255)),
                ('syringe_sharing', models.BooleanField(default=False)),
                ('sti_std', models.CharField(blank=True, max_length=255)),
                ('jaundice', models.BooleanField(default=False)),
                ('sex_with_sex_worker', models.BooleanField(default=False)),
                ('hiv_screening', models.BooleanField(default=False)),
                ('hiv_result', models.CharField(blank=True, max_length=255)),
                ('comorbid_medical_illness', models.TextField(blank=True)),
                ('comorbid_psychiatric_illness', models.TextField(blank=True)),
                ('previous_drug_treatment', models.CharField(blank=True, max_length=255)),
                ('ever_hospitalized', models.BooleanField(default=False)),
                ('addiction_type', models.CharField(choices=[('alcohol', 'Alcohol'), ('drugs', 'Drugs'), ('tobacco', 'Tobacco'), ('gambling', 'Gambling'), ('other', 'Other')], default='other', max_length=32)),
                ('addiction_duration', models.CharField(blank=True, max_length=255)),
                ('first_visit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=255)),
                ('family_history', models.TextField(blank=True)),
                ('medical_history', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('previous_treatments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['registration_number'],
                'indexes': [models.Index(fields=['registration_number'], name='patients_pa_registr_040bbc_idx'), models.Index(fields=['phone_number'], name='patients_pa_phone_n_933975_idx'), models.Index(fields=['full_name'], name='patients_pa_full_na_b75abe_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('aadhaar_number__isnull', False)), fields=('aadhaar_number',), name='unique_patient_aadhaar_when_present')],
            },
        ),
    ]
