# Generated by Django 6.0.4 on 2026-05-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_next_followup_date'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patient',
            new_name='patients_pa_next_fo_ee0511_idx',
            old_name='patients_pat_next_fo_9f6674_idx',
        ),
    ]
