# Generated by Django 6.0.4 on 2026-05-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_rename_registration_number_to_file_number'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_pa_registr_040bbc_idx',
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['file_number'], name='patients_pa_file_nu_158006_idx'),
        ),
    ]
