# Generated by Django 6.0.4 on 2026-06-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_patient_patients_pa_registr_040bbc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='do_not_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number_invalid',
            field=models.BooleanField(default=False),
        ),
    ]
