# Generated by Django 6.0.4 on 2026-06-16 08:38

import django.db.models.deletion
import django.db.models.functions.text
import staff.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='staff_designation_name_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_code', models.CharField(max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('locum', 'Locum'), ('contract', 'Contract')], default='permanent', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=16)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=staff.models.staff_photo_upload_path)),
                ('gov_registration', models.CharField(blank=True, default='', max_length=120)),
                ('aadhaar_number', models.CharField(blank=True, default='', max_length=20)),
                ('pan_number', models.CharField(blank=True, default='', max_length=20)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=40)),
                ('bank_ifsc', models.CharField(blank=True, default='', max_length=20)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('holiday_allowed', models.PositiveIntegerField(default=0)),
                ('sunday_holiday', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_created', to=settings.AUTH_USER_MODEL)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='staff.designation')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'ordering': ['staff_code'],
                'indexes': [models.Index(fields=['is_active'], name='staff_staff_is_acti_0db61a_idx'), models.Index(fields=['designation'], name='staff_staff_designa_cdd672_idx'), models.Index(fields=['full_name'], name='staff_staff_full_na_d63573_idx')],
            },
        ),
    ]
