# Generated by Django 6.0.4 on 2026-06-16 09:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staffattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('days_in_month', models.PositiveSmallIntegerField()),
                ('sundays_in_month', models.PositiveSmallIntegerField(default=0)),
                ('sunday_holiday', models.BooleanField(default=True)),
                ('holiday_allowed', models.PositiveIntegerField(default=0)),
                ('present_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('absent_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('half_days', models.PositiveSmallIntegerField(default=0)),
                ('paid_leave_used', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('unpaid_absent', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('per_day_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips_generated', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Payslip',
                'verbose_name_plural': 'Payslips',
                'ordering': ['-year', '-month', '-generated_at'],
                'indexes': [models.Index(fields=['staff', '-year', '-month'], name='staff_paysl_staff_i_e30a4e_idx')],
            },
        ),
    ]
