# Generated by Django 6.0.4 on 2026-06-13 20:48

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0006_remove_patient_patients_pa_registr_040bbc_idx_and_more'),
        ('pharmacy', '0009_dispenseinvoice_amount_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('default_consultation_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing Settings',
                'verbose_name_plural': 'Billing Settings',
            },
        ),
        migrations.CreateModel(
            name='PatientLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('charge', 'Charge (invoice billed)'), ('payment', 'Payment / Recovery'), ('adjustment', 'Adjustment / Reversal')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries_created', to=settings.AUTH_USER_MODEL)),
                ('dispense_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='pharmacy.dispenseinvoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient Ledger Entry',
                'verbose_name_plural': 'Patient Ledger Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', '-created_at'], name='billing_pat_patient_97cb12_idx'), models.Index(fields=['dispense_invoice'], name='billing_pat_dispens_e074e9_idx'), models.Index(fields=['entry_type'], name='billing_pat_entry_t_a8af61_idx')],
            },
        ),
    ]
