# Generated by Django 6.0.4 on 2026-04-09 21:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_uid', models.CharField(max_length=32, unique=True)),
                ('visit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('visit_type', models.CharField(default='follow_up', max_length=32)),
                ('checkin_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=32)),
                ('current_stage', models.CharField(choices=[('counsellor', 'Counsellor'), ('doctor', 'Doctor'), ('pharmacy', 'Pharmacy'), ('completed', 'Completed')], default='pharmacy', max_length=32)),
                ('outstanding_debt_at_checkin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medicines_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checked_in_sessions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-visit_date', '-checkin_time'],
                'indexes': [models.Index(fields=['visit_date', 'status'], name='visits_visi_visit_d_2799a6_idx'), models.Index(fields=['patient', 'visit_date'], name='visits_visi_patient_6b771c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('patient', 'visit_date'), name='unique_active_session_per_patient_per_day')],
            },
        ),
    ]
