# Generated by Django 6.0.4 on 2026-05-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visitsession_checkin_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitsession',
            name='file_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
