# Generated by Django 6.0.4 on 2026-05-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_visitsession_file_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitsession',
            name='verification_method',
            field=models.CharField(choices=[('fingerprint', 'Fingerprint'), ('photo', 'Photo'), ('manual', 'Manual')], default='fingerprint', max_length=16),
        ),
    ]
