# Generated by Django 6.0.4 on 2026-05-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='followupcallattempt',
            new_name='followups_f_ticket__1f611a_idx',
            old_name='followups_fo_ticket__54e9ec_idx',
        ),
        migrations.RenameIndex(
            model_name='followupticket',
            new_name='followups_f_patient_e07b7c_idx',
            old_name='followups_fo_patient_0f98d1_idx',
        ),
        migrations.RenameIndex(
            model_name='followupticket',
            new_name='followups_f_follow__0d3d68_idx',
            old_name='followups_fo_follow__b14557_idx',
        ),
        migrations.RenameIndex(
            model_name='followupticket',
            new_name='followups_f_next_ca_559d67_idx',
            old_name='followups_fo_next_ca_49ca95_idx',
        ),
    ]
